local signs = {
	ActiveTS = "綠",
	BufferClose = "",
	DapBreakpoint = "",
	DapBreakpointCondition = "",
	DapBreakpointRejected = "",
	DapLogPoint = ".>",
	DapStopped = "",
	DefaultFile = "",
	Diagnostic = "裂",
	DiagnosticError = "",
	DiagnosticHint = "",
	DiagnosticWarn = "",
	DiagnosticInfo = " ",
	FileModified = "",
	FileReadOnly = "",
	FolderClosed = "",
	FolderEmpty = "",
	FolderOpen = "",
	Git = "",
	GitAdd = "",
	GitBranch = "",
	GitChange = "",
	GitConflict = "",
	GitDelete = "",
	GitIgnored = "◌",
	GitRenamed = "➜",
	GitStaged = "✓",
	GitUnstaged = "✗",
	GitUntracked = "★",
	LSPLoaded = "",
	LSPLoading1 = "",
	LSPLoading2 = "",
	LSPLoading3 = "",
	MacroRecording = "",
	NeovimClose = "",
	Paste = "",
	Search = "",
	Selected = "❯",
	Spellcheck = "暈",
	ActiveLSP = "",
	Ellipsis = "…",
}

for type, icon in pairs(signs) do
	vim.fn.sign_define(type, { text = icon, texthl = type, numhl = "" })
end
